apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
    # https://argo-cd.readthedocs.io/en/latest/user-guide/app_deletion/#about-the-deletion-finalizer
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    # https://artifacthub.io/packages/helm/argo/argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: '8.3.0' # v3.1.0
    chart: argo-cd
    helm:
      releaseName: argocd
      valueFiles: values.yaml
  sources: []
  project: default
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
