---
# Restrict access to the "default" ArgoCD project
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
spec:
  sourceRepos:
  - "https://github.com/kristoferlundgren/argocd-apps.git"
  sourceNamespaces: []
  destinations:
  - namespace: argocd
    server: https://kubernetes.default.svc
  namespaceResourceBlacklist:
  - group: '*'
    kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra
spec:
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
