apiVersion: apps/v1
kind: Deployment
metadata:
  name: plantuml-server
  labels:
    app: plantuml-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plantuml-server
  template:
    metadata:
      labels:
        app: plantuml-server
    spec:
      containers:
      - name: plantuml-server
        image: plantuml/plantuml-server:jetty
        ports:
        - containerPort: 8080
